name: Django test
on:
  push:
    branches:
      -master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.7
    uses: actions/setup-python@v2
    with:
      python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
    - name: python testing
      run: |
        python manage.py test
        
    
    
    
    
    
      
